#!/usr/bin/env python3
"""
Generate dakota.in from params.yml.

Usage:
    python generate_dakota_in.py
"""

import yaml
from pathlib import Path

with open('params.yml') as f:
    cfg = yaml.safe_load(f)

dakota  = cfg['dakota']
modules = cfg.get('modules', {})

# Parameters owned by each module: disabled module → parameter fixed regardless
# of its own active flag.
_MODULE_PARAMS = {
    'snowpack':      ['PDD_melt_factor'],
    'frozen_ground': ['log__fdd_threshold', 'snow_insulation_k'],
    'direct_runoff': ['f_direct_runoff'],
    'rain_on_snow':  [],
}
for mod, param_names in _MODULE_PARAMS.items():
    if not modules.get(mod, True):
        for name in param_names:
            if name in cfg['parameters']:
                cfg['parameters'][name]['active'] = False

active  = {name: p for name, p in cfg['parameters'].items() if p['active']}
n       = len(active)

desc_str    = ' '.join(f"'{name}'" for name in active)
lower_str   = '  '.join(str(p['lower'])   for p in active.values())
upper_str   = '  '.join(str(p['upper'])   for p in active.values())
initial_str = '  '.join(str(p['initial']) for p in active.values())

param_comments = '\n'.join(
    f'#   {name}: {p["description"]}' for name, p in active.items()
)
inactive = {name: p for name, p in cfg['parameters'].items() if not p['active']}
fixed_comments = (
    '\n# Fixed (inactive) parameters:\n' +
    '\n'.join(f'#   {name} = {p["fixed"]}  ({p["description"]})'
              for name, p in inactive.items())
) if inactive else ''

content = f"""\
# Dakota input file: hydroRaVENS Cannon River parameter calibration
# Generated by generate_dakota_in.py from params.yml — do not edit by hand.
#
# Active parameters ({n}):
{param_comments}{fixed_comments}

environment
  top_method_pointer = 'HYBRID'
  tabular_data
    tabular_data_file = 'dakota.dat'

method
  id_method = 'HYBRID'
  hybrid sequential
    method_pointer_list = 'EGO' 'PS'

method
  id_method = 'EGO'
  efficient_global
    gaussian_process surfpack
    initial_samples = {dakota['ego_initial_samples']}
    seed = {dakota['ego_seed']}
    output quiet
  model_pointer = 'M1'

method
  id_method = 'PS'
  coliny_pattern_search
    max_function_evaluations = {dakota['ps_max_evaluations']}
    convergence_tolerance = {dakota['ps_convergence_tolerance']}
    output quiet
  model_pointer = 'M1'

model
  id_model = 'M1'
  single
    interface_pointer = 'I1'
  variables_pointer = 'V1'
  responses_pointer = 'R1'

variables
  id_variables = 'V1'
  continuous_design = {n}
    descriptors   = {desc_str}
    lower_bounds  =  {lower_str}
    upper_bounds  =  {upper_str}
    initial_point =  {initial_str}

interface
  id_interface = 'I1'
  analysis_driver = 'bash run_driver.sh'
  fork
    parameters_file = 'params.in'
    results_file    = 'results.out'
    work_directory
      named 'out/run'
      directory_tag
      directory_save
    file_save
    copy_files 'driver.py' 'cannon_cfg_template.yml' 'CannonTestInput.csv' 'run_driver.sh' 'params.yml'
    asynchronous
      evaluation_concurrency = {dakota['evaluation_concurrency']}

responses
  id_responses = 'R1'
  objective_functions = 1
    response_descriptors = 'neg_kge'
  no_gradients
  no_hessians
"""

Path('dakota.in').write_text(content)
print(f"Wrote dakota.in  ({n} active parameters)")
if inactive:
    print(f"Fixed parameters: {', '.join(inactive)}")
